/**
 * Bakerverse Theme Engine — Editor Serialiser
 *
 * Converts a Theme object into a valid `.theme.ts` module string.
 * The output compiles under TypeScript strict mode and exports a
 * constant that satisfies the Theme type.
 *
 * Round-trip guarantee:
 *   The generated module, when evaluated, produces an object equal
 *   (by deep JSON comparison) to the original Theme.
 *
 * Usage:
 *   const code = serializeTheme(myTheme);
 *   // → valid TypeScript module string, ready to save as foo.theme.ts
 */

import type { Theme } from '../schema';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a theme id to a safe JavaScript identifier for the export name.
 * e.g. "my-theme" → "myTheme"
 */
function idToExportName(id: string): string {
  const camel = id
    .toLowerCase()
    .replace(/[^a-z0-9]+([a-z])/g, (_match: string, char: string) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  // Ensure it starts with a lowercase letter
  return camel.charAt(0).toLowerCase() + camel.slice(1) + 'Theme';
}

/**
 * Indent every line of a string by the given number of spaces.
 */
function indent(str: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return str
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Serialise a Theme to a valid TypeScript module string.
 *
 * The output:
 * - Imports `Theme` from the schema
 * - Exports a typed constant whose name is derived from `theme.meta.id`
 * - Embeds the theme as `JSON.stringify` formatted literal (2-space indent)
 * - Includes a file-level comment with metadata
 *
 * @example
 * const code = serializeTheme(arcaneTheme);
 * // Produces:
 * //   import type { Theme } from '../schema';
 * //   export const arcaneTheme: Theme = { ... };
 */
export function serializeTheme(theme: Theme): string {
  const exportName = idToExportName(theme.meta.id);
  const jsonBody = indent(JSON.stringify(theme, null, 2), 0);

  return [
    '/**',
    ` * Bakerverse Theme — ${theme.meta.name}`,
    ` * Author: ${theme.meta.author}`,
    ` * Mood: ${theme.meta.mood}`,
    ` * Version: ${theme.meta.version}`,
    ` *`,
    ` * Generated by the Bakerverse theme editor.`,
    ` * Place this file in src/lib/theme/themes/ and register it in registry.ts.`,
    ' */',
    '',
    "import type { Theme } from '../schema';",
    '',
    `export const ${exportName}: Theme = ${jsonBody};`,
    '',
  ].join('\n');
}

/**
 * Derive the recommended file name for a serialised theme.
 * e.g. theme id "my-theme" → "my-theme.ts"
 */
export function themeFileName(theme: Theme): string {
  // Sanitise: keep only alphanumeric and hyphens
  const safe = theme.meta.id.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  return `${safe}.ts`;
}
