/**
 * Bakerverse Theme Engine — toCss
 *
 * Pure function: Theme → CSS string.
 *
 * Emits a `:root { … }` block whose variable names match the existing
 * `--bg-void` / `--gold-*` convention, so no downstream component code
 * needs changing when themes swap.
 *
 * Also emits:
 * - Static spacing scale (--space-0 … --space-32): not per-theme,
 *   identical across all themes, embedded here so the engine output is
 *   a complete replacement for tokens.css.
 * - RGB channel variants (--bg-night-rgb, --gold-300-rgb, …) for the
 *   palette entries that global.css uses in rgba() expressions. This
 *   allows global.css to be updated to `rgba(var(--gold-300-rgb), 0.06)`
 *   without hard-coding alpha-variants as separate named tokens.
 * - A @media (prefers-reduced-motion: reduce) override block that
 *   zeroes all duration tokens.
 */

import type { Theme } from './schema';

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/** Convert a 6-digit hex color to "r, g, b" channel string. */
function hexToRgbChannels(hex: string): string {
  const clean = hex.replace('#', '');
  const r = parseInt(clean.slice(0, 2), 16);
  const g = parseInt(clean.slice(2, 4), 16);
  const b = parseInt(clean.slice(4, 6), 16);
  return `${r}, ${g}, ${b}`;
}

/** Emit a CSS custom property line with consistent indentation. */
function prop(name: string, value: string): string {
  return `  ${name}: ${value};`;
}

/** Emit a CSS custom property + its RGB channel sibling (for hex colors). */
function colorProp(name: string, hex: string): string {
  const rgbName = `${name}-rgb`;
  // Only emit RGB variant for simple hex colors; pass through non-hex values
  if (/^#[0-9a-fA-F]{6}$/.test(hex)) {
    return [
      prop(name, hex),
      prop(rgbName, hexToRgbChannels(hex)),
    ].join('\n');
  }
  return prop(name, hex);
}

// ---------------------------------------------------------------------------
// static spacing scale (not per-theme)
// ---------------------------------------------------------------------------
const SPACING_BLOCK = `
  /* -- spacing scale (static — not per-theme) ------------------------- */
  --space-0:  0;
  --space-1:  0.25rem;
  --space-2:  0.5rem;
  --space-3:  0.75rem;
  --space-4:  1rem;
  --space-6:  1.5rem;
  --space-8:  2rem;
  --space-12: 3rem;
  --space-16: 4rem;
  --space-24: 6rem;
  --space-32: 8rem;`.trimStart();

// ---------------------------------------------------------------------------
// main export
// ---------------------------------------------------------------------------

/**
 * Convert a Theme object into a CSS string containing:
 * 1. A `:root { … }` block with all theme tokens + static spacing + RGB channels
 * 2. A `@media (prefers-reduced-motion: reduce)` block zeroing durations
 *
 * The output is deterministic (same input → same string), making it suitable
 * for SSR injection, snapshot testing, and hashing.
 */
export function toCss(theme: Theme): string {
  const { palette, typography, effects, motion } = theme;

  const lines: string[] = [
    '/* Bakerverse theme engine — generated by toCss() */',
    `:root {`,
    '',
    `  /* -- meta ----------------------------------------------------------- */`,
    `  --theme-id: "${theme.meta.id}";`,
    `  --theme-name: "${theme.meta.name}";`,
    `  --theme-appearance: "${theme.meta.appearance}";`,
    '',
    `  /* -- background scales ---------------------------------------------- */`,
    colorProp('--bg-void',  palette.bg.void),
    colorProp('--bg-night', palette.bg.night),
    colorProp('--bg-dusk',  palette.bg.dusk),
    colorProp('--bg-ember', palette.bg.ember),
    colorProp('--bg-stone', palette.bg.stone),
    '',
    `  /* -- ink (text) scales ---------------------------------------------- */`,
    colorProp('--ink-100', palette.ink['100']),
    colorProp('--ink-300', palette.ink['300']),
    colorProp('--ink-500', palette.ink['500']),
    colorProp('--ink-700', palette.ink['700']),
    '',
    `  /* -- primary scale (--gold-*) --------------------------------------- */`,
    colorProp('--gold-50',  palette.primary['50']),
    colorProp('--gold-100', palette.primary['100']),
    colorProp('--gold-200', palette.primary['200']),
    colorProp('--gold-300', palette.primary['300']),
    colorProp('--gold-400', palette.primary['400']),
    colorProp('--gold-500', palette.primary['500']),
    colorProp('--gold-600', palette.primary['600']),
    colorProp('--gold-700', palette.primary['700']),
    '',
    `  /* -- secondary scale (--purple-*) ----------------------------------- */`,
    colorProp('--purple-50',  palette.secondary['50']),
    colorProp('--purple-100', palette.secondary['100']),
    colorProp('--purple-200', palette.secondary['200']),
    colorProp('--purple-300', palette.secondary['300']),
    colorProp('--purple-400', palette.secondary['400']),
    colorProp('--purple-500', palette.secondary['500']),
    colorProp('--purple-600', palette.secondary['600']),
    colorProp('--purple-700', palette.secondary['700']),
    '',
    `  /* -- semantic alias ------------------------------------------------- */`,
    prop('--color-primary', palette.primary['400']),
    '',
    `  /* -- accents -------------------------------------------------------- */`,
    colorProp('--accent-purple', palette.accents.purple),
    colorProp('--accent-blood',  palette.accents.blood),
    colorProp('--accent-arcane', palette.accents.arcane),
    '',
    `  /* -- rarity (MMO loot tier) ----------------------------------------- */`,
    colorProp('--rarity-common',    palette.rarity.common),
    colorProp('--rarity-uncommon',  palette.rarity.uncommon),
    colorProp('--rarity-rare',      palette.rarity.rare),
    colorProp('--rarity-epic',      palette.rarity.epic),
    colorProp('--rarity-legendary', palette.rarity.legendary),
    colorProp('--rarity-artifact',  palette.rarity.artifact),
    '',
    `  /* -- radii ---------------------------------------------------------- */`,
    prop('--radius-sharp', effects.radii['sharp'] ?? '2px'),
    prop('--radius-soft',  effects.radii['soft']  ?? '8px'),
    prop('--radius-pill',  effects.radii['pill']  ?? '999px'),
    '',
    `  /* -- shadows -------------------------------------------------------- */`,
    prop('--shadow-tooltip',          effects.shadows['tooltip']          ?? ''),
    prop('--shadow-epic-glow',        effects.shadows['epic-glow']        ?? ''),
    prop('--shadow-epic-glow-strong', effects.shadows['epic-glow-strong'] ?? ''),
    prop('--shadow-inset-frame',      effects.shadows['inset-frame']      ?? ''),
    prop('--shadow-gold-glow',        effects.shadows['gold-glow']        ?? ''),
    prop('--shadow-gold-glow-strong', effects.shadows['gold-glow-strong'] ?? ''),
    '',
    `  /* -- motion --------------------------------------------------------- */`,
    prop('--ease-ornate',   motion.eases['ornate']   ?? 'cubic-bezier(0.19, 1, 0.22, 1)'),
    prop('--ease-bounce',   motion.eases['bounce']   ?? 'cubic-bezier(0.175, 0.885, 0.32, 1.275)'),
    prop('--ease-standard', motion.eases['standard'] ?? 'cubic-bezier(0.4, 0, 0.2, 1)'),
    '',
    prop('--dur-fast', motion.durations['fast'] ?? '150ms'),
    prop('--dur-base', motion.durations['base'] ?? '300ms'),
    prop('--dur-slow', motion.durations['slow'] ?? '500ms'),
    prop('--dur-page', motion.durations['page'] ?? '600ms'),
    '',
    `  /* -- typography ----------------------------------------------------- */`,
    prop('--font-display', typography.display),
    prop('--font-body',    typography.body),
    prop('--font-mono',    typography.mono),
    '',
    `  /* -- spacing scale (static) ----------------------------------------- */`,
    SPACING_BLOCK,
    '}',
    '',
    `/* Respect reduced motion globally. */`,
    `@media (prefers-reduced-motion: reduce) {`,
    `  :root {`,
    `    --dur-fast: 0ms;`,
    `    --dur-base: 0ms;`,
    `    --dur-slow: 0ms;`,
    `    --dur-page: 0ms;`,
    `  }`,
    `}`,
  ];

  return lines.join('\n');
}

/**
 * Returns a minimal inline script (no framework required) that reads
 * `localStorage.getItem('bakerverse.theme')` and sets `data-theme` on
 * `<html>` before first paint — eliminating FOUC.
 *
 * This script is intentionally tiny (<200B) and dependency-free.
 * It must be inserted as an inline `<script>` in the `<head>`.
 */
export function foucGuard(): string {
  return `(function(){try{var t=localStorage.getItem('bakerverse.theme');if(t)document.documentElement.setAttribute('data-theme',t);}catch(e){}})();`;
}
